[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
futures = "0.3.31"
protocol = { path = "../protocol" }
ratatui = "0.30.0"
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = {version = "0.7.17", features = ["codec"]}
