services:
  lb:
    build:
      context: .
      dockerfile: Dockerfile.lb
    environment:
      MCS_PORT: $MCS_PORT
      REDIS_URL: $REDIS_URL
    ports:
      - "${MCS_PORT}:${MCS_PORT}"
    depends_on:
      - server
    networks:
      - mcs-net

  db:
    image: postgres:latest
    container_name: mcs-postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - mcs-net

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    deploy:
      replicas: 2
    volumes:
      - ./tls:/app/tls
    environment:
      POSTGRES_URL: $POSTGRES_URL
      REDIS_URL: $REDIS_URL
    depends_on:
      - db
      - redis
    restart: on-failure
    networks:
      - mcs-net

  redis:
    image: redis:alpine
    networks:
      - mcs-net

networks:
  mcs-net:
