[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
chrono = "0.4.42"
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
